### ISSUE TITLE
Consistency of mutations

### ISSUE THREAD

**Issue by dm3** [MyPost/cassius#2]
After looking at Cassandra documentation and how the insertions/updates are implemented in Cassius, I have some concerns about the consistency of `put-in`/`mutate-in`.

According to [Cassandra sources](https://github.com/apache/cassandra/blob/ddd2ff7d63c9a9977eb2dd25936cecbb2ecd1cfb/interface/cassandra.thrift#L766), only `atomic_batch_mutate` guarantees that the batch will not fail in the middle of operation for the vast majority of cases (for failure modes see the [comments on Cassandra blog post](http://www.datastax.com/dev/blog/atomic-batches-in-cassandra-1-2)).

Obviously, this incurs a performance penalty of about ~30%. Is this the reason why Cassius uses `batch_mutate`? Would be nice if the mode was configurable.

**Comment by hoebat** [comment]
Hi Vadim,

Thanks for bringing forward this issue. You are right, we should be using more of atomic_batch_mutate. 

I guess that goes for drop-in and set-in as well :)

**Comment by hoebat** [comment]
Hi Valdim,

I'm had a play with this... just wanted your thoughts to see if this is what you were after. I've added an extra bit of logic to deal with the switching on 0.1.15-SNAPSHOT.

```
 (def conn (connect host port (assoc settings :atomic true)))
```

The pooling would have to be fixed to use a keyed pool instead of a normal pool. Everything should work as is.

the changes are here: https://github.com/MyPost/cassius/blob/master/src/cassius/net/command/mutate.clj

**Comment by dm3** [comment]
Thanks, that's exactly what I was looking for!
Not sure what you mean by "keyed pool instead of normal pool" though.
